### PR TITLE
updates

### PR DESCRIPTION
**Pull request by jhsiao999**

### CODE REVIEW

**Comment by jhsiao999** [comment]
@jdblischak Just FYI. I accidentally committed `rds` in there. There seems to be no problems with these files. So that's good...

**Comment by jdblischak** [comment]
I think they're going to be problematic again. The PR view hides it, but when you go to the actual file in your fork, you can see it's not uploaded:

https://github.com/jhsiao999/fucci-seq/blob/master/output/method-train-classifiers-top10.Rmd/fit.nw.unsup.split.rds

Did you use the conda or RCC version of `git-lfs` this time?

**Comment by jhsiao999** [comment]
Sorry... I think I might have added these in the terminal and not under the conda environment...

**Comment by jdblischak** [comment]
Unfortunately I don't have time to troubleshoot this at the moment. Could you please add a test `rds` file using the conda version of `git-lfs` and then push it to your GitHub fork? Please copy-paste the output from `git push` here and also include a link to this test file on GitHub.

**Comment by jhsiao999** [comment]
Here it is.

```
(fucci-seq) [joycehsiao@midway2-login1 fucci-seq]$ git push origin master
Username for 'https://github.com': jhsiao999
Password for 'https://jhsiao999@github.com': 
hint: The '.git/hooks/pre-push' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 56 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 502 bytes | 502.00 KiB/s, done.
Total 5 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/jhsiao999/fucci-seq.git
   c526f3f..7cf2011  master -> master
```

link to the file
```
https://github.com/jhsiao999/fucci-seq/blob/7cf2011aaaec90001d51827e576b7b6c13ad8444/output/method-labels.Rmd/pve.rda
```

**Comment by jdblischak** [comment]
Unfortunately that didn't seem to fix it. Something's not right.

https://github.com/jhsiao999/fucci-seq/blob/master/output/method-labels.Rmd/pve.rda

**Comment by jdblischak** [comment]
But a potential solution!

```
hint: The '.git/hooks/pre-push' hook was ignored because it's not set as executable.
```

That file needs to be executable (recall that we mucked with the permissions so that I could edit your repo).

Try this and copy-paste the output:

```
chmod a+x .git/hooks/pre-push
git push origin master
```

**Comment by jhsiao999** [comment]
```
(fucci-seq) [joycehsiao@midway2-login1 fucci-seq]$ chmod a+x .git/hooks/pre-push
(fucci-seq) [joycehsiao@midway2-login1 fucci-seq]$ git push origin master
Username for 'https://github.com': jhsiao999
Password for 'https://jhsiao999@github.com': 
Everything up-to-date
```

**Comment by jdblischak** [comment]
Maybe try `git lfs push`

**Comment by jhsiao999** [comment]
```
(fucci-seq) [joycehsiao@midway2-login1 fucci-seq]$ git lfs push origin master
Username for 'https://github.com': jhsiao999
Password for 'https://jhsiao999@github.com': 
(fucci-seq) [joycehsiao@midway2-login1 fucci-seq]$ 
```
nothing happened?

**Comment by jdblischak** [comment]
I found something else to try. I started getting the message `(%!s(MISSING))` when I ran `git lfs status`. Turns out this can be fixed by updating `git-lfs` (https://github.com/git-lfs/git-lfs/issues/2742), which fixed my issue.

Please try the following:

```
source activate fucci-seq
git lfs version
conda update -c conda-forge git-lfs
git lfs version
git lfs status
git lfs push
```

**Comment by jdblischak** [comment]
@jhsiao999 Did you try updating `git-lfs`?

**Comment by jhsiao999** [comment]
@jdblischak Just tried this. My `git lfs` is up-to-date. And there seems nothing to be pushed. 

```
(fucci-seq) [joycehsiao@midway2-login1 fucci-seq]$ git lfs version
git-lfs/2.4.2 (GitHub; linux amd64; go 1.10.2; git 6f4b2e98)
(fucci-seq) [joycehsiao@midway2-login1 fucci-seq]$ conda update -c conda-forge git-lfs
Solving environment: done

# All requested packages already installed.

(fucci-seq) [joycehsiao@midway2-login1 fucci-seq]$ git lfs status
On branch master
Git LFS objects to be pushed to origin/master:


Git LFS objects to be committed:


Git LFS objects not staged for commit:

	analysis/index.Rmd (Git: 6fccbf7 -> File: eaef2b6)
	code/working/job_all.sh (Git: 2401f63 -> File: 47e48f9)

(fucci-seq) [joycehsiao@midway2-login1 fucci-seq]$ git lfs push
Specify a remote and a remote branch name (`git lfs push origin master`)
(fucci-seq) [joycehsiao@midway2-login1 fucci-seq]$ git lfs push origin master
Username for 'https://github.com': jhsiao999
Password for 'https://jhsiao999@github.com': 
```

**Comment by jhsiao999** [comment]
what do you think if I re-make the rds in the last commit which was a `git lfs` and try `git lfs push again?

**Comment by jdblischak** [comment]
> Just tried this. My git lfs is up-to-date. And there seems nothing to be pushed.

Shoot. This is tough to troubleshoot.

> what do you think if I re-make the rds in the last commit which was a git lfs and try `git lfs push again?

The problem is that you've already committed them previously, so I don't think this will work.

Could you try making a test commit on a branch using the conda `git-lfs` to see if we still have the same problem?

```
source active fucci-seq
# Create a test branch
git checkout -b testing
# create a fake file
echo "testing" > data/testing.rds
git lfs status
git add data/testing.rds
git lfs status
git commit
git lfs status
git push origin testing
# Return to the master branch
git checkout master
```

**Comment by jhsiao999** [comment]
I got a warning after creating a new branch (haven't proceeded further yet)

```
(fucci-seq) [joycehsiao@midway2-login1 working]$ git checkout -b testing
M	analysis/index.Rmd
M	code/working/job_all.sh
Switched to a new branch 'testing'
hint: The '.git/hooks/post-checkout' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
```

**Comment by jdblischak** [comment]
Interesting. Before I had you make on the hooks executable, but it makes sense that they all need to be made executable. Try this:

```
chmod a+x .git/hooks/*
git lfs status
```

**Comment by jhsiao999** [comment]
```
(fucci-seq) [joycehsiao@midway2-login1 working]$ chmod a+x .git/hooks/*
chmod: cannot access ‘.git/hooks/*’: No such file or directory
(fucci-seq) [joycehsiao@midway2-login1 working]$ git lfs status
On branch testing

Git LFS objects to be committed:


Git LFS objects not staged for commit:

open analysis/index.Rmd: no such file or directory
```

**Comment by jdblischak** [comment]
The path `.git/hooks/*` is relative to the root of the fucci-seq project. It appears you are in the subdirectory `working` (you can confirm the current working directory with `pwd`). Here's an absolute path you can run from anywhere:

```
chmod a+x /project2/gilad/joycehsiao/fucci-seq/.git/hooks/*
```

**Comment by jhsiao999** [comment]
Okay that was run without warning. 

```
(fucci-seq) [joycehsiao@midway2-login1 working]$ chmod a+x /project2/gilad/joycehsiao/fucci-seq/.git/hooks/*
(fucci-seq) [joycehsiao@midway2-login1 working]$ git branch
  backup
  master
  mission_clean
* testing
(fucci-seq) [joycehsiao@midway2-login1 working]$ git lfs status
On branch testing

Git LFS objects to be committed:


Git LFS objects not staged for commit:

open analysis/index.Rmd: no such file or directory
```

**Comment by jhsiao999** [comment]
```
(fucci-seq) [joycehsiao@midway2-login1 fucci-seq]$ echo "testing" > data/testing.rds
(fucci-seq) [joycehsiao@midway2-login1 fucci-seq]$ git lfs status
On branch testing

Git LFS objects to be committed:


Git LFS objects not staged for commit:

	analysis/index.Rmd (Git: 6fccbf7 -> File: 51045d4)
	code/working/job_all.sh (Git: 2401f63 -> File: 47e48f9)

(fucci-seq) [joycehsiao@midway2-login1 fucci-seq]$ git add -f data/testing.rds
(fucci-seq) [joycehsiao@midway2-login1 fucci-seq]$ git lfs status
On branch testing

Git LFS objects to be committed:

	data/testing.rds (LFS: 12a61f4)

Git LFS objects not staged for commit:

	analysis/index.Rmd (Git: 6fccbf7 -> File: 51045d4)
	code/working/job_all.sh (Git: 2401f63 -> File: 47e48f9)

(fucci-seq) [joycehsiao@midway2-login1 fucci-seq]$ git commit 
[testing 5c6949c] test git-lfs
 1 file changed, 3 insertions(+)
 create mode 100644 data/testing.rds
(fucci-seq) [joycehsiao@midway2-login1 fucci-seq]$ git lfs status
On branch testing

Git LFS objects to be committed:


Git LFS objects not staged for commit:

	analysis/index.Rmd (Git: 6fccbf7 -> File: 51045d4)
	code/working/job_all.sh (Git: 2401f63 -> File: 47e48f9)

(fucci-seq) [joycehsiao@midway2-login1 fucci-seq]$ git push origin testing
Username for 'https://github.com': jhsiao999
Password for 'https://jhsiao999@github.com': 
Username for 'https://github.com': jhsiao999
Password for 'https://jhsiao999@github.com': 
Uploading LFS objects: 100% (1/1), 8 B | 0 B/s, done                                                                   
Enumerating objects: 12, done.
Counting objects: 100% (12/12), done.
Delta compression using up to 56 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 818 bytes | 409.00 KiB/s, done.
Total 8 (delta 5), reused 0 (delta 0)
remote: Resolving deltas: 100% (5/5), completed with 4 local objects.
To https://github.com/jhsiao999/fucci-seq.git
 * [new branch]      testing -> testing
(fucci-seq) [joycehsiao@midway2-login1 fucci-seq]$ git checkout master
M	analysis/index.Rmd
M	code/working/job_all.sh
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
(fucci-seq) [joycehsiao@midway2-login1 fucci-seq]$ git branch
  backup
* master
  mission_clean
  testing
```

**Comment by jhsiao999** [comment]
@jdblischak here's the link to the `rds`

https://github.com/jhsiao999/fucci-seq/blob/5c6949c91eff15e70af4d037e0f43745389f7ea4/data/testing.rds

I was able to click and download the `rds` file~

**Comment by jdblischak** [comment]
So it's a win that `git-lfs` is now operational. However, it only uploaded that one file:

```
Uploading LFS objects: 100% (1/1), 8 B | 0 B/s, done  
```

Now that you are back on the master branch, try `git push origin master` again just in case.

**Comment by jhsiao999** [comment]
do you mean push the `testing.rda` in the `testing` branch to the `master` branch?

**Comment by jdblischak** [comment]
> do you mean push the testing.rda in the testing branch to the master branch?

No, just pushing `master` to `master`

**Comment by jhsiao999** [comment]
```
[joycehsiao@midway2-login2 fucci-seq]$ git push origin master
Username for 'https://github.com': jhsiao999
Password for 'https://jhsiao999@github.com': 
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/jhsiao999/fucci-seq.git
   7cf2011..81caa6e  master -> master
[joycehsiao@midway2-login2 fucci-seq]$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   analysis/index.Rmd
	modified:   code/working/job_all.sh

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	analysis/cellcycler-seqdata-fucci.Rmd
	analysis/method-eval-bottcher.Rmd
	analysis/method-eval-buettner.Rmd
	analysis/method-eval-leng.Rmd
	analysis/method-eval-withheld-explore.Rmd
	analysis/method-eval-withheld-top10.Rmd
	analysis/method-eval-withheld.Rmd
	analysis/method-npreg.Rmd
	analysis/method-train-classifiers-all.Rmd
	analysis/norm-ercc-batch.Rmd
	analysis/norm-ercc-fucci.Rmd
	output/method-eval-withheld-explore.Rmd/
	output/method-eval-withheld-top10.Rmd/
	output/method-eval-withheld.Rmd/
	output/method-labels-seurat.Rmd/
	output/method-train-classifiers-all.Rmd/

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by jhsiao999** [comment]
I wonder if we should try to re-make and re-commit some of the `rds` files that we had trouble with? What do you think?

**Comment by jdblischak** [comment]
> I wonder if we should try to re-make and re-commit some of the rds files that we had trouble with? What do you think?

Seems worth a shot. Since the hooks weren't executable when you first added and committed the files, perhaps they just weren't registered with `git-lfs`. Try adding them again (unclear if you'll be able to commit them again since nothing has changed):

```
cd /project2/gilad/joycehsiao/fucci-seq
git add output/method-train-classifiers-top10.Rmd/fit.nw.unsup.split.rds
git status
git lfs status
```

**Comment by jdblischak** [comment]
Was `b.rds` a new file? That's the only one that worked recently.

**Comment by jhsiao999** [comment]
That was the first file that I tried. 

Subsequently I made small changes to the existing files, re-saved them and pushed them to the repo. And that seemed to work fine now. 

I am gonna go through all these `rds` files and do a PR for these. Hope it works then!

**Comment by jhsiao999** [comment]
@jdblischak The `rds` and `rda` files under `output/method-train-classifiers-top10.Rmd` have been re-committed. You can go ahead and merge this PR. 

I'll open a separate PR for the `rds` files created after these.  

Thanks so much! I think we are good now!

**Comment by jhsiao999** [comment]
@jdblischak I decided to do all the "old" updates in this PR. I checked the `rds` files added. I was able to downloaded them with new problems.

**Comment by jdblischak** [comment]
Great! I'm glad this appears to be fixed now. Do you know what is going on with [output/method-labels.Rmd/pve.rda](https://github.com/jhsiao999/fucci-seq/blob/0e2e0734a92287d887915ebb12f2184509a48b99/output/method-labels.Rmd/pve.rda)? It's the only one that doesn't appear to be uploaded properly.

**Comment by jhsiao999** [comment]
That is the one file that I missed. Just did a slight modification and re-saved it. All good now. Thanks!

**Comment by jdblischak** [comment]
Success!

It looks like the only issue was that the original versions of the files will never be available (since what was uploaded was your second commit of these files).

```
$ git push origin master
LFS upload missing objects: (12/21), 5.3 MB | 0 B/s                                                  
Uploading LFS objects:  57% (12/21), 5.3 MB | 0 B/s, done
  (missing) output/method-train-classifiers-top10.Rmd/fits.nw.rds (46b3c6e45120f5d79b8292667f403d8f58fd72c761c22b2b00ee0e8894fb6ca0)
  (missing) output/method-train-classifiers-top10.Rmd/fit.bspline.unsup.split.rds (83941334611c7613c472c08f83f3d315491dfa040f06f9e5dc79e0c1f7903e78)
  (missing) output/method-train-classifiers-top10.Rmd/fit.trend2.unsup.split.rds (d2611606d628c0ebcde31ffa0a19ff01d09c4c0fd529c43e6b7a224446210d80)
  (missing) output/method-labels.Rmd/pve.rda (0704ceaf73ec83eebe878f2ce10b2dd11ea77e74d35b37135ebd2fce9d446807)
  (missing) output/method-train-classifiers-top10.Rmd/pve.methods.unsupervised.split.rda (296f7b133de1261f44b8f7f10b5a14c447c2c8066ca92ebdf08d53122842d054)
  (missing) output/method-train-classifiers-top10.Rmd/fits.trend2.rds (2c6a43b208da1b0fac8aa7bbd036221a5e05193d804088be6fdd786c6ed884e7)
  (missing) output/method-train-classifiers-top10.Rmd/fit.nw.unsup.split.rds (f20ecc7305517a308d0f1dee45f95aca0d8fc1013d3d15f9036034ee1a8b3eb8)
  (missing) output/method-train-classifiers-top10.Rmd/fit.loess.unsup.split.rds (c3c4fa1b6a0ca7c9ce26fc22796c8fda8c3276a7e2d3fd9220badcbc789814ac)
  (missing) output/method-train-classifiers-top10.Rmd/pve.methods.rda (3131852474236497c10f1a0be8217cfe13a7871555b6d8386c058d2d10e5bd17)
Counting objects: 212, done.
Delta compression using up to 56 threads.
Compressing objects: 100% (98/98), done.
Writing objects: 100% (212/212), 6.87 MiB | 12.50 MiB/s, done.
Total 212 (delta 113), reused 212 (delta 113)
remote: Resolving deltas: 100% (113/113), completed with 24 local objects.
To github.com:jdblischak/fucci-seq.git
   4f91d84..b85ae8e  master -> master
$ git lfs status
On branch master
Git LFS objects to be pushed to origin/master:


Git LFS objects to be committed:


Git LFS objects not staged for commit:


$ git push origin master
Everything up-to-date
$ git pull origin master
From github.com:jdblischak/fucci-seq
 * branch            master     -> FETCH_HEAD
Already up-to-date.
```

**Comment by jdblischak** [comment]
Here's my theory of what caused this issue in the first place:

1. You used the Midway version of `git-lfs`, which is outdated, which failed to properly upload the LFS files.
2. When I had you edit the permissions of your Git repo so that I could edit it, we removed the executable permission of the hooks in `.git/hooks`, which are used by `git-lfs`.

Thus we fixed the problem by updating `git-lfs` in the conda environment and adding back the executable permission to the Git hooks.

Thank goodness it's working again!!!! :-)

**Pull request merged**
