### PR TITLE
updates

### PR DESCRIPTION
**Pull request by jhsiao999**

### CODE REVIEW

**Comment by jdblischak** [comment]
I'm having trouble understanding what happened. There is a conflict with one of the ExpressionSet objects, which you shouldn't have needed to changed. When you merged in the changes from this repo into your fork, what were the files with conflicting changes and how did you resolve them?

**Comment by jhsiao999** [comment]
That happened in the following commit. I did `git pull upstream master`, and then I was asked to do `git add` these files before I can do `git push`...

https://github.com/jdblischak/fucci-seq/pull/23/commits/8529d2e9003cdb8de6455bca6ceb34e21f69eb3d

**Comment by jhsiao999** [comment]
I didn't make any changes to these objects... Perhaps I should start clean and delete this eset object that has merge conflict and then do `git push` again...

**Comment by jdblischak** [comment]
On the master branch, I have 16 ExpressionSet objects with the following checksums:

```
$ git log -n 1 --oneline
da1fdf3 (HEAD -> master, origin/master, origin/HEAD) Build site.
$ md5sum data/eset/*
ed9b06a60e04d25fcaed8c54701debc5  data/eset/20170905.rds
32d536cd56c58755d492acab27147a84  data/eset/20170906.rds
1739df091cff8e692f0de5da812b7d75  data/eset/20170907.rds
8f61121fdc0bca9af0bf5403568db9bc  data/eset/20170908.rds
bee205273bbbd8d579bf1bf92423966e  data/eset/20170910.rds
13e3727babebafc69b7a2d086d59ee3f  data/eset/20170912.rds
ca28abb419122cf6a35739c7bf8f90ef  data/eset/20170913.rds
ecf46aae1dc0c17ea9573f408d958f81  data/eset/20170914.rds
82d9268f1b2a58775cede99fd7f31438  data/eset/20170915.rds
4116d34e2b15f11fb9c5015af5f0bb46  data/eset/20170916.rds
1b58d3c51205998fdf1ff89f5cb4b350  data/eset/20170917.rds
bd88f0ed2569dea0561037143f48d439  data/eset/20170919.rds
e378bf952504ed68c660078b2ec718d4  data/eset/20170920.rds
390b6e7089d8003d5d6acd2fd1ad03dc  data/eset/20170921.rds
ff3dd9e3761b88e7cdb39394349b01b6  data/eset/20170922.rds
0428652b7e8977a441d7d498cc0345ce  data/eset/20170924.rds
```

On your master branch, there are 15 ExpressionSet objects (`20170910.rds` is missing). Only the first 4 checksums match the master branch:

```
$ git log -n 1 --oneline
861e367 (HEAD, jhsiao999/master) add Leng subsampling results
$ md5sum data/eset/*
ed9b06a60e04d25fcaed8c54701debc5  data/eset/20170905.rds
32d536cd56c58755d492acab27147a84  data/eset/20170906.rds
1739df091cff8e692f0de5da812b7d75  data/eset/20170907.rds
8f61121fdc0bca9af0bf5403568db9bc  data/eset/20170908.rds
6c22f6823902af9e00528fc48680b703  data/eset/20170912.rds
a2d8db180a9295d0c70b9eff24ca30c1  data/eset/20170913.rds
5e663f949286cab341ef1faf8102ec4e  data/eset/20170914.rds
df4e5d406ef5fe33ab596cf6b30a735b  data/eset/20170915.rds
556a6852a711c0d7fb9d6499d2a1abef  data/eset/20170916.rds
09d16eec7f10df5d26a418094e19f114  data/eset/20170917.rds
88a50728c2e4350fb4a9250db7c31781  data/eset/20170919.rds
113691831b7bd285d8e3d1a8192a81c1  data/eset/20170920.rds
f363dd6acce946b05d1bacd350185472  data/eset/20170921.rds
f51f247729dc5dfb8cdb061a9e39ed5e  data/eset/20170922.rds
4fd425de81a4d8eb03919521d660c6bd  data/eset/20170924.rds
```

These results are consistent with your commit https://github.com/jdblischak/fucci-seq/commit/8529d2e9003cdb8de6455bca6ceb34e21f69eb3d. In that commit, you updated the first 4 files and deleted the 5th. The remaining files didn't get updated, so maybe you ran `git checkout` or `git reset` to remove the changes?

**Pull request merged**
